# Generated by Django 3.2.18 on 2023-04-22 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20230422_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
